CREATE DATABASE EDH;
USE EDH;
CREATE TABLE Users(
FirstName VARCHAR(255) NOT NULL, 
LastName VARCHAR(255) NOT NULL, 
PhoneNumber VARCHAR(255),
Email VARCHAR(225) NOT NULL,
Street VARCHAR(255) NOT NULL, 
City VARCHAR(255) NOT NULL, 
State VARCHAR(255) NOT NULL,
ZipCode VARCHAR(5) NOT NULL, 
CONSTRAINT PK_Users PRIMARY KEY (FirstName, LastName, Email) 
); 
